root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2018","WGJets_MonoPhoton_PtG-40to130UL","loose")'
root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2018","WGJets_MonoPhoton_PtG-130UL","loose")'
root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2016postVFP","WGJets_MonoPhoton_PtG-40to130UL","loose")'
root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2016postVFP","WGJets_MonoPhoton_PtG-130UL","loose")'

root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2017","WGJets_MonoPhoton_PtG-40to130UL","loose")'
root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2017","WGJets_MonoPhoton_PtG-130UL","loose")'

root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_WJetsToLNu_HT_v1.txt",1,"2018","WJetsToLNu_HTUL","loose")'
root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_WJetsToLNu_HT_v1.txt",1,"2017","WJetsToLNu_HTUL","loose")'
root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_WJetsToLNu_HT_v1.txt",1,"2016postVFP","WJetsToLNu_HTUL","loose")'

root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_TTJets_inc_v1.txt",1,"2018","TTJets_incUL","loose")'
root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_TTJets_inc_v1.txt",1,"2017","TTJets_incUL","loose")'
root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_TTJets_inc_v1.txt",1,"2016postVFP","TTJets_incUL","loose")'

root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_TTJets_HT_v1.txt",1,"2018","TTJets_HTUL","loose")'
root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_TTJets_HT_v1.txt",1,"2017","TTJets_HTUL","loose")'
root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_TTJets_HT_v1.txt",1,"2016postVFP","TTJets_HTUL","loose")'

root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_TTGJets_inc_v1.txt",1,"2018","TTGJets_incUL","loose")'
root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_TTGJets_inc_v1.txt",1,"2017","TTGJets_incUL","loose")'
root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_TTGJets_inc_v1.txt",1,"2016postVFP","TTGJets_incUL","loose")'
root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_TTGJets_inc_v1.txt",1,"2016preVFP","TTGJets_incUL","loose")'
root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_TTJets_HT_v1.txt",1,"2016preVFP","TTJets_HTUL","loose")'
root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_TTJets_inc_v1.txt",1,"2016preVFP","TTJets_incUL","loose")'
root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_WJetsToLNu_HT_v1.txt",1,"2016preVFP","WJetsToLNu_HTUL","loose")'
root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2016preVFP","WGJets_MonoPhoton_PtG-40to130UL","loose")'
root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2016preVFP","WGJets_MonoPhoton_PtG-130UL","loose")'

root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_ST.txt",1,"2018","STUL","loose")'
root -l	-q 'splitRunList.C("runList_skimmed_Summer20UL17_ST.txt",1,"2017","STUL","loose")'
root -l	-q 'splitRunList.C("runList_skimmed_Summer20UL16_ST.txt",1,"2016postVFP","STUL","loose")'
root -l	-q 'splitRunList.C("runList_skimmed_Summer20UL16APV_ST.txt",1,"2016preVFP","STUL","loose")'

# # ## Systematic studies
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2018","WGJets_MonoPhoton_PtG-40to130UL","looseCrossSecDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2018","WGJets_MonoPhoton_PtG-130UL","looseCrossSecDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2016postVFP","WGJets_MonoPhoton_PtG-40to130UL","looseCrossSecDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2016postVFP","WGJets_MonoPhoton_PtG-130UL","looseCrossSecDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2017","WGJets_MonoPhoton_PtG-40to130UL","looseCrossSecDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2017","WGJets_MonoPhoton_PtG-130UL","looseCrossSecDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_WJetsToLNu_HT_v1.txt",1,"2018","WJetsToLNu_HTUL","looseCrossSecDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_WJetsToLNu_HT_v1.txt",1,"2017","WJetsToLNu_HTUL","looseCrossSecDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_WJetsToLNu_HT_v1.txt",1,"2016postVFP","WJetsToLNu_HTUL","looseCrossSecDown")'

# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_TTJets_inc_v1.txt",1,"2018","TTJets_incUL","looseCrossSecDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_TTJets_inc_v1.txt",1,"2017","TTJets_incUL","looseCrossSecDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_TTJets_inc_v1.txt",1,"2016postVFP","TTJets_incUL","looseCrossSecDown")'

# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_TTJets_HT_v1.txt",1,"2018","TTJets_HTUL","looseCrossSecDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_TTJets_HT_v1.txt",1,"2017","TTJets_HTUL","looseCrossSecDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_TTJets_HT_v1.txt",1,"2016postVFP","TTJets_HTUL","looseCrossSecDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_TTGJets_inc_v1.txt",1,"2018","TTGJets_incUL","looseCrossSecDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_TTGJets_inc_v1.txt",1,"2017","TTGJets_incUL","looseCrossSecDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_TTGJets_inc_v1.txt",1,"2016postVFP","TTGJets_incUL","looseCrossSecDown")'

# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_TTGJets_inc_v1.txt",1,"2016preVFP","TTGJets_incUL","looseCrossSecDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_TTJets_HT_v1.txt",1,"2016preVFP","TTJets_HTUL","looseCrossSecDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_TTJets_inc_v1.txt",1,"2016preVFP","TTJets_incUL","looseCrossSecDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_WJetsToLNu_HT_v1.txt",1,"2016preVFP","WJetsToLNu_HTUL","looseCrossSecDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2016preVFP","WGJets_MonoPhoton_PtG-40to130UL","looseCrossSecDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2016preVFP","WGJets_MonoPhoton_PtG-130UL","looseCrossSecDown")'

# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_ST.txt",1,"2018","STUL","looseCrossSecDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_ST.txt",1,"2017","STUL","looseCrossSecDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_ST.txt",1,"2016postVFP","STUL","looseCrossSecDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_ST.txt",1,"2016preVFP","STUL","looseCrossSecDown")'

# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2018","WGJets_MonoPhoton_PtG-40to130UL","looseCrossSecUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2018","WGJets_MonoPhoton_PtG-130UL","looseCrossSecUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2016postVFP","WGJets_MonoPhoton_PtG-40to130UL","looseCrossSecUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2016postVFP","WGJets_MonoPhoton_PtG-130UL","looseCrossSecUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2017","WGJets_MonoPhoton_PtG-40to130UL","looseCrossSecUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2017","WGJets_MonoPhoton_PtG-130UL","looseCrossSecUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_WJetsToLNu_HT_v1.txt",1,"2018","WJetsToLNu_HTUL","looseCrossSecUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_WJetsToLNu_HT_v1.txt",1,"2017","WJetsToLNu_HTUL","looseCrossSecUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_WJetsToLNu_HT_v1.txt",1,"2016postVFP","WJetsToLNu_HTUL","looseCrossSecUp")'

# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_TTJets_inc_v1.txt",1,"2018","TTJets_incUL","looseCrossSecUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_TTJets_inc_v1.txt",1,"2017","TTJets_incUL","looseCrossSecUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_TTJets_inc_v1.txt",1,"2016postVFP","TTJets_incUL","looseCrossSecUp")'

# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_TTJets_HT_v1.txt",1,"2018","TTJets_HTUL","looseCrossSecUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_TTJets_HT_v1.txt",1,"2017","TTJets_HTUL","looseCrossSecUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_TTJets_HT_v1.txt",1,"2016postVFP","TTJets_HTUL","looseCrossSecUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_TTGJets_inc_v1.txt",1,"2018","TTGJets_incUL","looseCrossSecUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_TTGJets_inc_v1.txt",1,"2017","TTGJets_incUL","looseCrossSecUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_TTGJets_inc_v1.txt",1,"2016postVFP","TTGJets_incUL","looseCrossSecUp")'

# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_TTGJets_inc_v1.txt",1,"2016preVFP","TTGJets_incUL","looseCrossSecUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_TTJets_HT_v1.txt",1,"2016preVFP","TTJets_HTUL","looseCrossSecUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_TTJets_inc_v1.txt",1,"2016preVFP","TTJets_incUL","looseCrossSecUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_WJetsToLNu_HT_v1.txt",1,"2016preVFP","WJetsToLNu_HTUL","looseCrossSecUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2016preVFP","WGJets_MonoPhoton_PtG-40to130UL","looseCrossSecUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2016preVFP","WGJets_MonoPhoton_PtG-130UL","looseCrossSecUp")'

# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_ST.txt",1,"2018","STUL","looseCrossSecUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_ST.txt",1,"2017","STUL","looseCrossSecUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_ST.txt",1,"2016postVFP","STUL","looseCrossSecUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_ST.txt",1,"2016preVFP","STUL","looseCrossSecUp")'


# # JET EC
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2018","WGJets_MonoPhoton_PtG-40to130UL","looseJetSys_JECup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2018","WGJets_MonoPhoton_PtG-130UL","looseJetSys_JECup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2016postVFP","WGJets_MonoPhoton_PtG-40to130UL","looseJetSys_JECup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2016postVFP","WGJets_MonoPhoton_PtG-130UL","looseJetSys_JECup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2017","WGJets_MonoPhoton_PtG-40to130UL","looseJetSys_JECup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2017","WGJets_MonoPhoton_PtG-130UL","looseJetSys_JECup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_WJetsToLNu_HT_v1.txt",1,"2018","WJetsToLNu_HTUL","looseJetSys_JECup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_WJetsToLNu_HT_v1.txt",1,"2017","WJetsToLNu_HTUL","looseJetSys_JECup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_WJetsToLNu_HT_v1.txt",1,"2016postVFP","WJetsToLNu_HTUL","looseJetSys_JECup")'

# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_TTJets_inc_v1.txt",1,"2018","TTJets_incUL","looseJetSys_JECup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_TTJets_inc_v1.txt",1,"2017","TTJets_incUL","looseJetSys_JECup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_TTJets_inc_v1.txt",1,"2016postVFP","TTJets_incUL","looseJetSys_JECup")'

# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_TTJets_HT_v1.txt",1,"2018","TTJets_HTUL","looseJetSys_JECup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_TTJets_HT_v1.txt",1,"2017","TTJets_HTUL","looseJetSys_JECup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_TTJets_HT_v1.txt",1,"2016postVFP","TTJets_HTUL","looseJetSys_JECup")'
# root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_TTGJets_inc_v1.txt",1,"2018","TTGJets_incUL","looseJetSys_JECup")'
# root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_TTGJets_inc_v1.txt",1,"2017","TTGJets_incUL","looseJetSys_JECup")'
# root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_TTGJets_inc_v1.txt",1,"2016postVFP","TTGJets_incUL","looseJetSys_JECup")'

# root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_TTGJets_inc_v1.txt",1,"2016preVFP","TTGJets_incUL","looseJetSys_JECup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_TTJets_HT_v1.txt",1,"2016preVFP","TTJets_HTUL","looseJetSys_JECup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_TTJets_inc_v1.txt",1,"2016preVFP","TTJets_incUL","looseJetSys_JECup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_WJetsToLNu_HT_v1.txt",1,"2016preVFP","WJetsToLNu_HTUL","looseJetSys_JECup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2016preVFP","WGJets_MonoPhoton_PtG-40to130UL","looseJetSys_JECup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2016preVFP","WGJets_MonoPhoton_PtG-130UL","looseJetSys_JECup")'

# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_ST.txt",1,"2018","STUL","looseJetSys_JECup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_ST.txt",1,"2017","STUL","looseJetSys_JECup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_ST.txt",1,"2016postVFP","STUL","looseJetSys_JECup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_ST.txt",1,"2016preVFP","STUL","looseJetSys_JECup")'


# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2018","WGJets_MonoPhoton_PtG-40to130UL","looseJetSys_JECdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2018","WGJets_MonoPhoton_PtG-130UL","looseJetSys_JECdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2016postVFP","WGJets_MonoPhoton_PtG-40to130UL","looseJetSys_JECdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2016postVFP","WGJets_MonoPhoton_PtG-130UL","looseJetSys_JECdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2017","WGJets_MonoPhoton_PtG-40to130UL","looseJetSys_JECdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2017","WGJets_MonoPhoton_PtG-130UL","looseJetSys_JECdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_WJetsToLNu_HT_v1.txt",1,"2018","WJetsToLNu_HTUL","looseJetSys_JECdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_WJetsToLNu_HT_v1.txt",1,"2017","WJetsToLNu_HTUL","looseJetSys_JECdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_WJetsToLNu_HT_v1.txt",1,"2016postVFP","WJetsToLNu_HTUL","looseJetSys_JECdown")'

# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_TTJets_inc_v1.txt",1,"2018","TTJets_incUL","looseJetSys_JECdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_TTJets_inc_v1.txt",1,"2017","TTJets_incUL","looseJetSys_JECdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_TTJets_inc_v1.txt",1,"2016postVFP","TTJets_incUL","looseJetSys_JECdown")'

# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_TTJets_HT_v1.txt",1,"2018","TTJets_HTUL","looseJetSys_JECdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_TTJets_HT_v1.txt",1,"2017","TTJets_HTUL","looseJetSys_JECdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_TTJets_HT_v1.txt",1,"2016postVFP","TTJets_HTUL","looseJetSys_JECdown")'
# root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_TTGJets_inc_v1.txt",1,"2018","TTGJets_incUL","looseJetSys_JECdown")'
# root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_TTGJets_inc_v1.txt",1,"2017","TTGJets_incUL","looseJetSys_JECdown")'
# root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_TTGJets_inc_v1.txt",1,"2016postVFP","TTGJets_incUL","looseJetSys_JECdown")'

# root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_TTGJets_inc_v1.txt",1,"2016preVFP","TTGJets_incUL","looseJetSys_JECdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_TTJets_HT_v1.txt",1,"2016preVFP","TTJets_HTUL","looseJetSys_JECdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_TTJets_inc_v1.txt",1,"2016preVFP","TTJets_incUL","looseJetSys_JECdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_WJetsToLNu_HT_v1.txt",1,"2016preVFP","WJetsToLNu_HTUL","looseJetSys_JECdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2016preVFP","WGJets_MonoPhoton_PtG-40to130UL","looseJetSys_JECdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2016preVFP","WGJets_MonoPhoton_PtG-130UL","looseJetSys_JECdown")'

# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_ST.txt",1,"2018","STUL","looseJetSys_JECdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_ST.txt",1,"2017","STUL","looseJetSys_JECdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_ST.txt",1,"2016postVFP","STUL","looseJetSys_JECdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_ST.txt",1,"2016preVFP","STUL","looseJetSys_JECdown")'


# # JER
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2018","WGJets_MonoPhoton_PtG-40to130UL","looseJetSys_JERdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2018","WGJets_MonoPhoton_PtG-130UL","looseJetSys_JERdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2016postVFP","WGJets_MonoPhoton_PtG-40to130UL","looseJetSys_JERdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2016postVFP","WGJets_MonoPhoton_PtG-130UL","looseJetSys_JERdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2017","WGJets_MonoPhoton_PtG-40to130UL","looseJetSys_JERdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2017","WGJets_MonoPhoton_PtG-130UL","looseJetSys_JERdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_WJetsToLNu_HT_v1.txt",1,"2018","WJetsToLNu_HTUL","looseJetSys_JERdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_WJetsToLNu_HT_v1.txt",1,"2017","WJetsToLNu_HTUL","looseJetSys_JERdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_WJetsToLNu_HT_v1.txt",1,"2016postVFP","WJetsToLNu_HTUL","looseJetSys_JERdown")'

# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_TTJets_inc_v1.txt",1,"2018","TTJets_incUL","looseJetSys_JERdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_TTJets_inc_v1.txt",1,"2017","TTJets_incUL","looseJetSys_JERdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_TTJets_inc_v1.txt",1,"2016postVFP","TTJets_incUL","looseJetSys_JERdown")'

# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_TTJets_HT_v1.txt",1,"2018","TTJets_HTUL","looseJetSys_JERdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_TTJets_HT_v1.txt",1,"2017","TTJets_HTUL","looseJetSys_JERdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_TTJets_HT_v1.txt",1,"2016postVFP","TTJets_HTUL","looseJetSys_JERdown")'
# root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_TTGJets_inc_v1.txt",1,"2018","TTGJets_incUL","looseJetSys_JERdown")'
# root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_TTGJets_inc_v1.txt",1,"2017","TTGJets_incUL","looseJetSys_JERdown")'
# root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_TTGJets_inc_v1.txt",1,"2016postVFP","TTGJets_incUL","looseJetSys_JERdown")'

# root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_TTGJets_inc_v1.txt",1,"2016preVFP","TTGJets_incUL","looseJetSys_JERdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_TTJets_HT_v1.txt",1,"2016preVFP","TTJets_HTUL","looseJetSys_JERdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_TTJets_inc_v1.txt",1,"2016preVFP","TTJets_incUL","looseJetSys_JERdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_WJetsToLNu_HT_v1.txt",1,"2016preVFP","WJetsToLNu_HTUL","looseJetSys_JERdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2016preVFP","WGJets_MonoPhoton_PtG-40to130UL","looseJetSys_JERdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2016preVFP","WGJets_MonoPhoton_PtG-130UL","looseJetSys_JERdown")'

# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_ST.txt",1,"2018","STUL","looseJetSys_JERdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_ST.txt",1,"2017","STUL","looseJetSys_JERdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_ST.txt",1,"2016postVFP","STUL","looseJetSys_JERdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_ST.txt",1,"2016preVFP","STUL","looseJetSys_JERdown")'


# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2018","WGJets_MonoPhoton_PtG-40to130UL","looseJetSys_JERup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2018","WGJets_MonoPhoton_PtG-130UL","looseJetSys_JERup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2016postVFP","WGJets_MonoPhoton_PtG-40to130UL","looseJetSys_JERup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2016postVFP","WGJets_MonoPhoton_PtG-130UL","looseJetSys_JERup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2017","WGJets_MonoPhoton_PtG-40to130UL","looseJetSys_JERup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2017","WGJets_MonoPhoton_PtG-130UL","looseJetSys_JERup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_WJetsToLNu_HT_v1.txt",1,"2018","WJetsToLNu_HTUL","looseJetSys_JERup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_WJetsToLNu_HT_v1.txt",1,"2017","WJetsToLNu_HTUL","looseJetSys_JERup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_WJetsToLNu_HT_v1.txt",1,"2016postVFP","WJetsToLNu_HTUL","looseJetSys_JERup")'

# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_TTJets_inc_v1.txt",1,"2018","TTJets_incUL","looseJetSys_JERup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_TTJets_inc_v1.txt",1,"2017","TTJets_incUL","looseJetSys_JERup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_TTJets_inc_v1.txt",1,"2016postVFP","TTJets_incUL","looseJetSys_JERup")'

# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_TTJets_HT_v1.txt",1,"2018","TTJets_HTUL","looseJetSys_JERup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_TTJets_HT_v1.txt",1,"2017","TTJets_HTUL","looseJetSys_JERup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_TTJets_HT_v1.txt",1,"2016postVFP","TTJets_HTUL","looseJetSys_JERup")'
# root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_TTGJets_inc_v1.txt",1,"2018","TTGJets_incUL","looseJetSys_JERup")'
# root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_TTGJets_inc_v1.txt",1,"2017","TTGJets_incUL","looseJetSys_JERup")'
# root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_TTGJets_inc_v1.txt",1,"2016postVFP","TTGJets_incUL","looseJetSys_JERup")'

# root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_TTGJets_inc_v1.txt",1,"2016preVFP","TTGJets_incUL","looseJetSys_JERup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_TTJets_HT_v1.txt",1,"2016preVFP","TTJets_HTUL","looseJetSys_JERup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_TTJets_inc_v1.txt",1,"2016preVFP","TTJets_incUL","looseJetSys_JERup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_WJetsToLNu_HT_v1.txt",1,"2016preVFP","WJetsToLNu_HTUL","looseJetSys_JERup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2016preVFP","WGJets_MonoPhoton_PtG-40to130UL","looseJetSys_JERup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2016preVFP","WGJets_MonoPhoton_PtG-130UL","looseJetSys_JERup")'

# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_ST.txt",1,"2018","STUL","looseJetSys_JERup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_ST.txt",1,"2017","STUL","looseJetSys_JERup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_ST.txt",1,"2016postVFP","STUL","looseJetSys_JERup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_ST.txt",1,"2016preVFP","STUL","looseJetSys_JERup")'


# # ####pileup
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2018","WGJets_MonoPhoton_PtG-40to130UL","loosepuSysDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2018","WGJets_MonoPhoton_PtG-130UL","loosepuSysDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2016postVFP","WGJets_MonoPhoton_PtG-40to130UL","loosepuSysDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2016postVFP","WGJets_MonoPhoton_PtG-130UL","loosepuSysDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2017","WGJets_MonoPhoton_PtG-40to130UL","loosepuSysDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2017","WGJets_MonoPhoton_PtG-130UL","loosepuSysDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_WJetsToLNu_HT_v1.txt",1,"2018","WJetsToLNu_HTUL","loosepuSysDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_WJetsToLNu_HT_v1.txt",1,"2017","WJetsToLNu_HTUL","loosepuSysDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_WJetsToLNu_HT_v1.txt",1,"2016postVFP","WJetsToLNu_HTUL","loosepuSysDown")'

# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_TTJets_inc_v1.txt",1,"2018","TTJets_incUL","loosepuSysDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_TTJets_inc_v1.txt",1,"2017","TTJets_incUL","loosepuSysDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_TTJets_inc_v1.txt",1,"2016postVFP","TTJets_incUL","loosepuSysDown")'

# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_TTJets_HT_v1.txt",1,"2018","TTJets_HTUL","loosepuSysDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_TTJets_HT_v1.txt",1,"2017","TTJets_HTUL","loosepuSysDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_TTJets_HT_v1.txt",1,"2016postVFP","TTJets_HTUL","loosepuSysDown")'
# root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_TTGJets_inc_v1.txt",1,"2018","TTGJets_incUL","loosepuSysDown")'
# root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_TTGJets_inc_v1.txt",1,"2017","TTGJets_incUL","loosepuSysDown")'
# root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_TTGJets_inc_v1.txt",1,"2016postVFP","TTGJets_incUL","loosepuSysDown")'

# root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_TTGJets_inc_v1.txt",1,"2016preVFP","TTGJets_incUL","loosepuSysDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_TTJets_HT_v1.txt",1,"2016preVFP","TTJets_HTUL","loosepuSysDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_TTJets_inc_v1.txt",1,"2016preVFP","TTJets_incUL","loosepuSysDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_WJetsToLNu_HT_v1.txt",1,"2016preVFP","WJetsToLNu_HTUL","loosepuSysDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2016preVFP","WGJets_MonoPhoton_PtG-40to130UL","loosepuSysDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2016preVFP","WGJets_MonoPhoton_PtG-130UL","loosepuSysDown")'

# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_ST.txt",1,"2018","STUL","loosepuSysDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_ST.txt",1,"2017","STUL","loosepuSysDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_ST.txt",1,"2016postVFP","STUL","loosepuSysDown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_ST.txt",1,"2016preVFP","STUL","loosepuSysDown")'


# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2018","WGJets_MonoPhoton_PtG-40to130UL","loosepuSysUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2018","WGJets_MonoPhoton_PtG-130UL","loosepuSysUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2016postVFP","WGJets_MonoPhoton_PtG-40to130UL","loosepuSysUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2016postVFP","WGJets_MonoPhoton_PtG-130UL","loosepuSysUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2017","WGJets_MonoPhoton_PtG-40to130UL","loosepuSysUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2017","WGJets_MonoPhoton_PtG-130UL","loosepuSysUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_WJetsToLNu_HT_v1.txt",1,"2018","WJetsToLNu_HTUL","loosepuSysUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_WJetsToLNu_HT_v1.txt",1,"2017","WJetsToLNu_HTUL","loosepuSysUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_WJetsToLNu_HT_v1.txt",1,"2016postVFP","WJetsToLNu_HTUL","loosepuSysUp")'

# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_TTJets_inc_v1.txt",1,"2018","TTJets_incUL","loosepuSysUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_TTJets_inc_v1.txt",1,"2017","TTJets_incUL","loosepuSysUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_TTJets_inc_v1.txt",1,"2016postVFP","TTJets_incUL","loosepuSysUp")'

# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_TTJets_HT_v1.txt",1,"2018","TTJets_HTUL","loosepuSysUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_TTJets_HT_v1.txt",1,"2017","TTJets_HTUL","loosepuSysUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_TTJets_HT_v1.txt",1,"2016postVFP","TTJets_HTUL","loosepuSysUp")'
# root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_TTGJets_inc_v1.txt",1,"2018","TTGJets_incUL","loosepuSysUp")'
# root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_TTGJets_inc_v1.txt",1,"2017","TTGJets_incUL","loosepuSysUp")'
# root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_TTGJets_inc_v1.txt",1,"2016postVFP","TTGJets_incUL","loosepuSysUp")'

# root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_TTGJets_inc_v1.txt",1,"2016preVFP","TTGJets_incUL","loosepuSysUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_TTJets_HT_v1.txt",1,"2016preVFP","TTJets_HTUL","loosepuSysUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_TTJets_inc_v1.txt",1,"2016preVFP","TTJets_incUL","loosepuSysUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_WJetsToLNu_HT_v1.txt",1,"2016preVFP","WJetsToLNu_HTUL","loosepuSysUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2016preVFP","WGJets_MonoPhoton_PtG-40to130UL","loosepuSysUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2016preVFP","WGJets_MonoPhoton_PtG-130UL","loosepuSysUp")'

# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_ST.txt",1,"2018","STUL","loosepuSysUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_ST.txt",1,"2017","STUL","loosepuSysUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_ST.txt",1,"2016postVFP","STUL","loosepuSysUp")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_ST.txt",1,"2016preVFP","STUL","loosepuSysUp")'



# # ###btag SF
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2018","WGJets_MonoPhoton_PtG-40to130UL","loosebtagSFup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2018","WGJets_MonoPhoton_PtG-130UL","loosebtagSFup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2016postVFP","WGJets_MonoPhoton_PtG-40to130UL","loosebtagSFup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2016postVFP","WGJets_MonoPhoton_PtG-130UL","loosebtagSFup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2017","WGJets_MonoPhoton_PtG-40to130UL","loosebtagSFup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2017","WGJets_MonoPhoton_PtG-130UL","loosebtagSFup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_WJetsToLNu_HT_v1.txt",1,"2018","WJetsToLNu_HTUL","loosebtagSFup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_WJetsToLNu_HT_v1.txt",1,"2017","WJetsToLNu_HTUL","loosebtagSFup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_WJetsToLNu_HT_v1.txt",1,"2016postVFP","WJetsToLNu_HTUL","loosebtagSFup")'

# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_TTJets_inc_v1.txt",1,"2018","TTJets_incUL","loosebtagSFup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_TTJets_inc_v1.txt",1,"2017","TTJets_incUL","loosebtagSFup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_TTJets_inc_v1.txt",1,"2016postVFP","TTJets_incUL","loosebtagSFup")'

# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_TTJets_HT_v1.txt",1,"2018","TTJets_HTUL","loosebtagSFup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_TTJets_HT_v1.txt",1,"2017","TTJets_HTUL","loosebtagSFup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_TTJets_HT_v1.txt",1,"2016postVFP","TTJets_HTUL","loosebtagSFup")'
# root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_TTGJets_inc_v1.txt",1,"2018","TTGJets_incUL","loosebtagSFup")'
# root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_TTGJets_inc_v1.txt",1,"2017","TTGJets_incUL","loosebtagSFup")'
# root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_TTGJets_inc_v1.txt",1,"2016postVFP","TTGJets_incUL","loosebtagSFup")'

# root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_TTGJets_inc_v1.txt",1,"2016preVFP","TTGJets_incUL","loosebtagSFup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_TTJets_HT_v1.txt",1,"2016preVFP","TTJets_HTUL","loosebtagSFup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_TTJets_inc_v1.txt",1,"2016preVFP","TTJets_incUL","loosebtagSFup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_WJetsToLNu_HT_v1.txt",1,"2016preVFP","WJetsToLNu_HTUL","loosebtagSFup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2016preVFP","WGJets_MonoPhoton_PtG-40to130UL","loosebtagSFup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2016preVFP","WGJets_MonoPhoton_PtG-130UL","loosebtagSFup")'

# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_ST.txt",1,"2018","STUL","loosebtagSFup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_ST.txt",1,"2017","STUL","loosebtagSFup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_ST.txt",1,"2016postVFP","STUL","loosebtagSFup")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_ST.txt",1,"2016preVFP","STUL","loosebtagSFup")'


# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2018","WGJets_MonoPhoton_PtG-40to130UL","loosebtagSFdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2018","WGJets_MonoPhoton_PtG-130UL","loosebtagSFdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2016postVFP","WGJets_MonoPhoton_PtG-40to130UL","loosebtagSFdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2016postVFP","WGJets_MonoPhoton_PtG-130UL","loosebtagSFdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2017","WGJets_MonoPhoton_PtG-40to130UL","loosebtagSFdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2017","WGJets_MonoPhoton_PtG-130UL","loosebtagSFdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_WJetsToLNu_HT_v1.txt",1,"2018","WJetsToLNu_HTUL","loosebtagSFdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_WJetsToLNu_HT_v1.txt",1,"2017","WJetsToLNu_HTUL","loosebtagSFdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_WJetsToLNu_HT_v1.txt",1,"2016postVFP","WJetsToLNu_HTUL","loosebtagSFdown")'

# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_TTJets_inc_v1.txt",1,"2018","TTJets_incUL","loosebtagSFdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_TTJets_inc_v1.txt",1,"2017","TTJets_incUL","loosebtagSFdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_TTJets_inc_v1.txt",1,"2016postVFP","TTJets_incUL","loosebtagSFdown")'

# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_TTJets_HT_v1.txt",1,"2018","TTJets_HTUL","loosebtagSFdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_TTJets_HT_v1.txt",1,"2017","TTJets_HTUL","loosebtagSFdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_TTJets_HT_v1.txt",1,"2016postVFP","TTJets_HTUL","loosebtagSFdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_TTGJets_inc_v1.txt",1,"2018","TTGJets_incUL","loosebtagSFdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_TTGJets_inc_v1.txt",1,"2017","TTGJets_incUL","loosebtagSFdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_TTGJets_inc_v1.txt",1,"2016postVFP","TTGJets_incUL","loosebtagSFdown")'

# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_TTGJets_inc_v1.txt",1,"2016preVFP","TTGJets_incUL","loosebtagSFdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_TTJets_HT_v1.txt",1,"2016preVFP","TTJets_HTUL","loosebtagSFdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_TTJets_inc_v1.txt",1,"2016preVFP","TTJets_incUL","loosebtagSFdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_WJetsToLNu_HT_v1.txt",1,"2016preVFP","WJetsToLNu_HTUL","loosebtagSFdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_WGJets_MonoPhoton_PtG-40to130_v1.txt",1,"2016preVFP","WGJets_MonoPhoton_PtG-40to130UL","loosebtagSFdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_WGJets_MonoPhoton_PtG-130_v1.txt",1,"2016preVFP","WGJets_MonoPhoton_PtG-130UL","loosebtagSFdown")'

# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL18_ST.txt",1,"2018","STUL","loosebtagSFdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL17_ST.txt",1,"2017","STUL","loosebtagSFdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16_ST.txt",1,"2016postVFP","STUL","loosebtagSFdown")'
# # root -l -q 'splitRunList.C("runList_skimmed_Summer20UL16APV_ST.txt",1,"2016preVFP","STUL","loosebtagSFdown")'




