#  hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16_TTJets_SingleLeptFromTbar_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16_TTJets_SingleLeptFromTbar_TuneCP5_13TeV-madgraphMLM-pythia8'`
# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16_TTJets_SingleLeptFromT_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16_TTJets_SingleLeptFromT_TuneCP5_13TeV-madgraphMLM-pythia8'`
# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16_TTJets_DiLept_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16_TTJets_DiLept_TuneCP5_13TeV-madgraphMLM-pythia8'`
# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16_TTJets_HT-600to800_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16_TTJets_HT-600to800_TuneCP5_13TeV-madgraphMLM-pythia8'`
# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16_TTJets_HT-800to1200_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16_TTJets_HT-800to1200_TuneCP5_13TeV-madgraphMLM-pythia8'`
# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16_TTJets_HT-1200to2500_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16_TTJets_HT-1200to2500_TuneCP5_13TeV-madgraphMLM-pythia8'`
# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16_TTJets_HT-2500toInf_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16_TTJets_HT-2500toInf_TuneCP5_13TeV-madgraphMLM-pythia8'`

# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16_TTGJets_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16_TTGJets'`

# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16_WJetsToLNu_HT-100To200_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16_WJetsToLNu_HT-100To200_TuneCP5_13TeV-madgraphMLM-pythia8'`
# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16_WJetsToLNu_HT-200To400_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16_WJetsToLNu_HT-200To400_TuneCP5_13TeV-madgraphMLM-pythia8'`
# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16_WJetsToLNu_HT-400To600_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16_WJetsToLNu_HT-400To600_TuneCP5_13TeV-madgraphMLM-pythia8'`

# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16_WJetsToLNu_HT-600To800_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16_WJetsToLNu_HT-600To800_TuneCP5_13TeV-madgraphMLM-pythia8'`

# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16_WJetsToLNu_HT-800To1200_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16_WJetsToLNu_HT-800To1200_TuneCP5_13TeV-madgraphMLM-pythia8'`
# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16_WJetsToLNu_HT-1200To2500_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16_WJetsToLNu_HT-1200To2500_TuneCP5_13TeV-madgraphMLM-pythia8'`

# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16_WJetsToLNu_HT-2500ToInf_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16_WJetsToLNu_HT-2500ToInf_TuneCP5_13TeV-madgraphMLM-pythia8'`

# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16_WGJets_MonoPhoton_PtG-40to130_TuneCP5_13TeV-madgraph-pythia8.root `xrdfsls -u  /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16_WGJets_MonoPhoton_PtG-40to130_TuneCP5_13TeV'`

# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16_WGJets_MonoPhoton_PtG-130_TuneCP5_13TeV-madgraph-pythia8.root `xrdfsls -u  /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16_WGJets_MonoPhoton_PtG-130_TuneCP5_13TeV'`

# # hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16_ST_tW_top_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16_ST_tW_top_5f_inclusiveDecays'`
# # hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16_ST_tW_antitop_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16_ST_tW_antitop_5f_inclusiveDecays'`

# # hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16_ST_t-channel_top_5f_InclusiveDecays_TuneCP5_13TeV-powheg-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16_ST_t-channel_top_5f_InclusiveDecays'`
# # hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16_ST_t-channel_antitop_5f_InclusiveDecays_TuneCP5_13TeV-powheg-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16_ST_t-channel_antitop_5f_InclusiveDecays'`
# # hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16_ST_s-channel_4f_leptonDecays_TuneCP5_13TeV-powheg-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16_ST_s-channel_4f_leptonDecays'`

# #hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16_ST_s


# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16APV_TTJets_SingleLeptFromTbar_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16APV_TTJets_SingleLeptFromTbar_TuneCP5_13TeV-madgraphMLM-pythia8'`
# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16APV_TTJets_SingleLeptFromT_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16APV_TTJets_SingleLeptFromT_TuneCP5_13TeV-madgraphMLM-pythia8'`
# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16APV_TTJets_DiLept_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16APV_TTJets_DiLept_TuneCP5_13TeV-madgraphMLM-pythia8'`
# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16APV_TTJets_HT-600to800_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16APV_TTJets_HT-600to800_TuneCP5_13TeV-madgraphMLM-pythia8'`
# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16APV_TTJets_HT-800to1200_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16APV_TTJets_HT-800to1200_TuneCP5_13TeV-madgraphMLM-pythia8'`
# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16APV_TTJets_HT-1200to2500_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16APV_TTJets_HT-1200to2500_TuneCP5_13TeV-madgraphMLM-pythia8'`
# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16APV_TTJets_HT-2500toInf_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16APV_TTJets_HT-2500toInf_TuneCP5_13TeV-madgraphMLM-pythia8'`

# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16APV_TTGJets_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16APV_TTGJets'`

# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16APV_WJetsToLNu_HT-100To200_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16APV_WJetsToLNu_HT-100To200_TuneCP5_13TeV-madgraphMLM-pythia8'`
# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16APV_WJetsToLNu_HT-200To400_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16APV_WJetsToLNu_HT-200To400_TuneCP5_13TeV-madgraphMLM-pythia8'`
# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16APV_WJetsToLNu_HT-400To600_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16APV_WJetsToLNu_HT-400To600_TuneCP5_13TeV-madgraphMLM-pythia8'`

# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16APV_WJetsToLNu_HT-600To800_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16APV_WJetsToLNu_HT-600To800_TuneCP5_13TeV-madgraphMLM-pythia8'`

# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16APV_WJetsToLNu_HT-800To1200_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16APV_WJetsToLNu_HT-800To1200_TuneCP5_13TeV-madgraphMLM-pythia8'`
# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16APV_WJetsToLNu_HT-1200To2500_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16APV_WJetsToLNu_HT-1200To2500_TuneCP5_13TeV-madgraphMLM-pythia8'`

# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16APV_WJetsToLNu_HT-2500ToInf_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16APV_WJetsToLNu_HT-2500ToInf_TuneCP5_13TeV-madgraphMLM-pythia8'`

# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16APV_WGJets_MonoPhoton_PtG-40to130_TuneCP5_13TeV-madgraph-pythia8.root `xrdfsls -u  /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16APV_WGJets_MonoPhoton_PtG-40to130_TuneCP5_13TeV'`

# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16APV_WGJets_MonoPhoton_PtG-130_TuneCP5_13TeV-madgraph-pythia8.root `xrdfsls -u  /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16APV_WGJets_MonoPhoton_PtG-130_TuneCP5_13TeV'`

# # hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16APV_ST_tW_top_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16APV_ST_tW_top_5f_inclusiveDecays'`
# # hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16APV_ST_tW_antitop_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16APV_ST_tW_antitop_5f_inclusiveDecays'`

# # hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16APV_ST_t-channel_top_5f_InclusiveDecays_TuneCP5_13TeV-powheg-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16APV_ST_t-channel_top_5f_InclusiveDecays'`
# # hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16APV_ST_t-channel_antitop_5f_InclusiveDecays_TuneCP5_13TeV-powheg-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16APV_ST_t-channel_antitop_5f_InclusiveDecays'`
# # hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16APV_ST_s-channel_4f_leptonDecays_TuneCP5_13TeV-powheg-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL16APV_ST_s-channel_4f_leptonDecays'`


# # #hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16APV_ST_s





# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL17_TTJets_SingleLeptFromTbar_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL17_TTJets_SingleLeptFromTbar_TuneCP5_13TeV-madgraphMLM-pythia8'`
# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL17_TTJets_SingleLeptFromT_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL17_TTJets_SingleLeptFromT_TuneCP5_13TeV-madgraphMLM-pythia8'`
# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL17_TTJets_DiLept_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL17_TTJets_DiLept_TuneCP5_13TeV-madgraphMLM-pythia8'`
# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL17_TTJets_HT-600to800_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL17_TTJets_HT-600to800_TuneCP5_13TeV-madgraphMLM-pythia8'`
# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL17_TTJets_HT-800to1200_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL17_TTJets_HT-800to1200_TuneCP5_13TeV-madgraphMLM-pythia8'`
# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL17_TTJets_HT-1200to2500_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL17_TTJets_HT-1200to2500_TuneCP5_13TeV-madgraphMLM-pythia8'`
# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL17_TTJets_HT-2500toInf_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL17_TTJets_HT-2500toInf_TuneCP5_13TeV-madgraphMLM-pythia8'`

# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL17_TTGJets_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL17_TTGJets'`

# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL17_WJetsToLNu_HT-100To200_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL17_WJetsToLNu_HT-100To200_TuneCP5_13TeV-madgraphMLM-pythia8'`
# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL17_WJetsToLNu_HT-200To400_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL17_WJetsToLNu_HT-200To400_TuneCP5_13TeV-madgraphMLM-pythia8'`
# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL17_WJetsToLNu_HT-400To600_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL17_WJetsToLNu_HT-400To600_TuneCP5_13TeV-madgraphMLM-pythia8'`

# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL17_WJetsToLNu_HT-600To800_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL17_WJetsToLNu_HT-600To800_TuneCP5_13TeV-madgraphMLM-pythia8'`

# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL17_WJetsToLNu_HT-800To1200_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL17_WJetsToLNu_HT-800To1200_TuneCP5_13TeV-madgraphMLM-pythia8'`
# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL17_WJetsToLNu_HT-1200To2500_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL17_WJetsToLNu_HT-1200To2500_TuneCP5_13TeV-madgraphMLM-pythia8'`

# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL17_WJetsToLNu_HT-2500ToInf_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL17_WJetsToLNu_HT-2500ToInf_TuneCP5_13TeV-madgraphMLM-pythia8'`

# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL17_WGJets_MonoPhoton_PtG-40to130_TuneCP5_13TeV-madgraph-pythia8.root `xrdfsls -u  /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL17_WGJets_MonoPhoton_PtG-40to130_TuneCP5_13TeV'`

# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL17_WGJets_MonoPhoton_PtG-130_TuneCP5_13TeV-madgraph-pythia8.root `xrdfsls -u  /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL17_WGJets_MonoPhoton_PtG-130_TuneCP5_13TeV'`

# # hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL17_ST_tW_top_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL17_ST_tW_top_5f_inclusiveDecays'`
# # hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL17_ST_tW_antitop_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL17_ST_tW_antitop_5f_inclusiveDecays'`

# # hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL17_ST_t-channel_top_5f_InclusiveDecays_TuneCP5_13TeV-powheg-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL17_ST_t-channel_top_5f_InclusiveDecays'`
# # hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL17_ST_t-channel_antitop_5f_InclusiveDecays_TuneCP5_13TeV-powheg-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL17_ST_t-channel_antitop_5f_InclusiveDecays'`
# # hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL17_ST_s-channel_4f_leptonDecays_TuneCP5_13TeV-powheg-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL17_ST_s-channel_4f_leptonDecays'`


# #hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL17_ST_s





hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL18_TTJets_SingleLeptFromTbar_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL18_TTJets_SingleLeptFromTbar_TuneCP5_13TeV-madgraphMLM-pythia8'`
#hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL18_TTJets_SingleLeptFromT_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL18_TTJets_SingleLeptFromT_TuneCP5_13TeV-madgraphMLM-pythia8'`
#hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL18_TTJets_DiLept_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL18_TTJets_DiLept_TuneCP5_13TeV-madgraphMLM-pythia8'`
# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL18_TTJets_HT-600to800_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL18_TTJets_HT-600to800_TuneCP5_13TeV-madgraphMLM-pythia8'`
# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL18_TTJets_HT-800to1200_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL18_TTJets_HT-800to1200_TuneCP5_13TeV-madgraphMLM-pythia8'`
# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL18_TTJets_HT-1200to2500_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL18_TTJets_HT-1200to2500_TuneCP5_13TeV-madgraphMLM-pythia8'`
hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL18_TTJets_HT-2500toInf_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL18_TTJets_HT-2500toInf_TuneCP5_13TeV-madgraphMLM-pythia8'`

hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL18_TTGJets_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL18_TTGJets'`

# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL18_WJetsToLNu_HT-100To200_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL18_WJetsToLNu_HT-100To200_TuneCP5_13TeV-madgraphMLM-pythia8'`
hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL18_WJetsToLNu_HT-200To400_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL18_WJetsToLNu_HT-200To400_TuneCP5_13TeV-madgraphMLM-pythia8'`
# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL18_WJetsToLNu_HT-400To600_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL18_WJetsToLNu_HT-400To600_TuneCP5_13TeV-madgraphMLM-pythia8'`

# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL18_WJetsToLNu_HT-600To800_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL18_WJetsToLNu_HT-600To800_TuneCP5_13TeV-madgraphMLM-pythia8'`

hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL18_WJetsToLNu_HT-800To1200_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL18_WJetsToLNu_HT-800To1200_TuneCP5_13TeV-madgraphMLM-pythia8'`
# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL18_WJetsToLNu_HT-1200To2500_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL18_WJetsToLNu_HT-1200To2500_TuneCP5_13TeV-madgraphMLM-pythia8'`

# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL18_WJetsToLNu_HT-2500ToInf_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL18_WJetsToLNu_HT-2500ToInf_TuneCP5_13TeV-madgraphMLM-pythia8'`

hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL18_WGJets_MonoPhoton_PtG-40to130_TuneCP5_13TeV-madgraph-pythia8.root `xrdfsls -u  /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL18_WGJets_MonoPhoton_PtG-40to130_TuneCP5_13TeV'`

# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL18_WGJets_MonoPhoton_PtG-130_TuneCP5_13TeV-madgraph-pythia8.root `xrdfsls -u  /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL18_WGJets_MonoPhoton_PtG-130_TuneCP5_13TeV'`

# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL18_ST_tW_top_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL18_ST_tW_top_5f_inclusiveDecays'`
# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL18_ST_tW_antitop_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL18_ST_tW_antitop_5f_inclusiveDecays'`

# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL18_ST_t-channel_top_5f_InclusiveDecays_TuneCP5_13TeV-powheg-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL18_ST_t-channel_top_5f_InclusiveDecays'`
# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL18_ST_t-channel_antitop_5f_InclusiveDecays_TuneCP5_13TeV-powheg-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL18_ST_t-channel_antitop_5f_InclusiveDecays'`
# hadd -f /eos/uscms/store/user/lpcsusyphotons/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL18_ST_s-channel_4f_leptonDecays_TuneCP5_13TeV-powheg-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/kalpana/ULSkims_June23/v1_WithMakeClass/FR | grep 'phoID_loose_runList_Summer20UL18_ST_s-channel_4f_leptonDecays'`
