# hadd -fk /eos/uscms/store/user/lpcsusyphotons/SoftPhoton/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL18_ST_s-channel_4f_leptonDecays_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/SoftPhoton/kalpana/ULSkims_June23/FR | grep 'phoID_loose_runList_Summer20UL18_ST_s-channel_4f_leptonDecays'`

# hadd -fk /eos/uscms/store/user/lpcsusyphotons/SoftPhoton/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL17_ST_s-channel_4f_leptonDecays_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/SoftPhoton/kalpana/ULSkims_June23/FR | grep 'phoID_loose_runList_Summer20UL17_ST_s-channel_4f_leptonDecays'`                                                                                                                           
# hadd -fk /eos/uscms/store/user/lpcsusyphotons/SoftPhoton/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16_ST_s-channel_4f_leptonDecays_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/SoftPhoton/kalpana/ULSkims_June23/FR | grep 'phoID_loose_runList_Summer20UL16_ST_s-channel_4f_leptonDecays'`                                                                                                                           
# hadd -fk /eos/uscms/store/user/lpcsusyphotons/SoftPhoton/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16APV_ST_s-channel_4f_leptonDecays_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/SoftPhoton/kalpana/ULSkims_June23/FR | grep 'phoID_loose_runList_Summer20UL16APV_ST_s-channel_4f_leptonDecays'`                                                                                                                     


# hadd -fk /eos/uscms/store/user/lpcsusyphotons/SoftPhoton/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL18_ST_t-channel_antitop_5f_InclusiveDecays_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/SoftPhoton/kalpana/ULSkims_June23/FR | grep 'phoID_loose_runList_Summer20UL18_ST_t-channel_antitop_5f_InclusiveDecays'`
# hadd -fk /eos/uscms/store/user/lpcsusyphotons/SoftPhoton/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL17_ST_t-channel_antitop_5f_InclusiveDecays_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/SoftPhoton/kalpana/ULSkims_June23/FR | grep 'phoID_loose_runList_Summer20UL17_ST_t-channel_antitop_5f_InclusiveDecays'`                                                                                                                                                                                                                                     
# hadd -fk /eos/uscms/store/user/lpcsusyphotons/SoftPhoton/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16_ST_t-channel_antitop_5f_InclusiveDecays_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/SoftPhoton/kalpana/ULSkims_June23/FR | grep 'phoID_loose_runList_Summer20UL16_ST_t-channel_antitop_5f_InclusiveDecays'`                                                                                                                                                                                                                                     
# hadd -fk /eos/uscms/store/user/lpcsusyphotons/SoftPhoton/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16APV_ST_t-channel_antitop_5f_InclusiveDecays_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/SoftPhoton/kalpana/ULSkims_June23/FR | grep 'phoID_loose_runList_Summer20UL16APV_ST_t-channel_antitop_5f_InclusiveDecays'`



# hadd -fk /eos/uscms/store/user/lpcsusyphotons/SoftPhoton/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL18_ST_t-channel_top_5f_InclusiveDecays_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/SoftPhoton/kalpana/ULSkims_June23/FR | grep 'phoID_loose_runList_Summer20UL18_ST_t-channel_top_5f_InclusiveDecays'`                                                                                                                                                                                                                                             
# hadd -fk /eos/uscms/store/user/lpcsusyphotons/SoftPhoton/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL17_ST_t-channel_top_5f_InclusiveDecays_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/SoftPhoton/kalpana/ULSkims_June23/FR | grep 'phoID_loose_runList_Summer20UL17_ST_t-channel_top_5f_InclusiveDecays'`                                                                                                                                                                                                                                             
# hadd -fk /eos/uscms/store/user/lpcsusyphotons/SoftPhoton/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16_ST_t-channel_top_5f_InclusiveDecays_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/SoftPhoton/kalpana/ULSkims_June23/FR | grep 'phoID_loose_runList_Summer20UL16_ST_t-channel_top_5f_InclusiveDecays'`                                                                                                                                                                                                                                             
# hadd -fk /eos/uscms/store/user/lpcsusyphotons/SoftPhoton/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16APV_ST_t-channel_top_5f_InclusiveDecays_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/SoftPhoton/kalpana/ULSkims_June23/FR | grep 'phoID_loose_runList_Summer20UL16APV_ST_t-channel_top_5f_InclusiveDecays'`                                                                                                                                                                                                                                       



# hadd -fk /eos/uscms/store/user/lpcsusyphotons/SoftPhoton/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL18_ST_tW_antitop_5f_inclusiveDecays_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/SoftPhoton/kalpana/ULSkims_June23/FR | grep 'phoID_loose_runList_Summer20UL18_ST_tW_antitop_5f_inclusiveDecays'`                                                                                                                                                                                                                                             
# hadd -fk /eos/uscms/store/user/lpcsusyphotons/SoftPhoton/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL17_ST_tW_antitop_5f_inclusiveDecays_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/SoftPhoton/kalpana/ULSkims_June23/FR | grep 'phoID_loose_runList_Summer20UL17_ST_tW_antitop_5f_inclusiveDecays'`                                                                                                                                                                                                                                                 
# hadd -fk /eos/uscms/store/user/lpcsusyphotons/SoftPhoton/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16_ST_tW_antitop_5f_inclusiveDecays_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/SoftPhoton/kalpana/ULSkims_June23/FR | grep 'phoID_loose_runList_Summer20UL16_ST_tW_antitop_5f_inclusiveDecays'`                                                                                                                   
# hadd -fk /eos/uscms/store/user/lpcsusyphotons/SoftPhoton/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16APV_ST_tW_antitop_5f_inclusiveDecays_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/SoftPhoton/kalpana/ULSkims_June23/FR | grep 'phoID_loose_runList_Summer20UL16APV_ST_tW_antitop_5f_inclusiveDecays'`


# hadd -fk /eos/uscms/store/user/lpcsusyphotons/SoftPhoton/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL18_ST_tW_top_5f_inclusiveDecays_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/SoftPhoton/kalpana/ULSkims_June23/FR | grep 'phoID_loose_runList_Summer20UL18_ST_tW_top_5f_inclusiveDecays'`                                                                                                                           
# hadd -fk /eos/uscms/store/user/lpcsusyphotons/SoftPhoton/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL17_ST_tW_top_5f_inclusiveDecays_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/SoftPhoton/kalpana/ULSkims_June23/FR | grep 'phoID_loose_runList_Summer20UL17_ST_tW_top_5f_inclusiveDecays'`                                                                                                                           
# hadd -fk /eos/uscms/store/user/lpcsusyphotons/SoftPhoton/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16_ST_tW_top_5f_inclusiveDecays_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/SoftPhoton/kalpana/ULSkims_June23/FR | grep 'phoID_loose_runList_Summer20UL16_ST_tW_top_5f_inclusiveDecays'`                                                                                                                           
# hadd -fk /eos/uscms/store/user/lpcsusyphotons/SoftPhoton/kalpana/SkimsUL_June2023/FR/skimmed_Summer20UL16APV_ST_tW_top_5f_inclusiveDecays_TuneCP5_13TeV-madgraphMLM-pythia8.root `xrdfsls -u /store/user/lpcsusyphotons/SoftPhoton/kalpana/ULSkims_June23/FR | grep 'phoID_loose_runList_Summer20UL16APV_ST_tW_top_5f_inclusiveDecays'`
