// Class: ReadBDT_200trees_2maxdepth
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT_200trees_2maxdepth
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.26/11       [399883]
Creator        : kalpana
Date           : Thu Jul  4 02:49:34 2024
Host           : Linux cmsbuild107.cern.ch 4.18.0-477.13.1.el8_8.x86_64 #1 SMP Tue May 30 14:53:41 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /uscms_data/d3/kalpana/public/work/Susy_lowPho_analysis/CMSSW_14_0_0_pre0/src/BDT_optmizationSignalvsBkg_v17/BDT_Training
Training events: 670251
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NTrees: "200" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
nCuts: "-1" [Number of grid points in variable range used in finding optimal cut in node splitting]
# Default:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for BoostType=Grad algorithm]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "3" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 7
MET                           MET                           MET                           MET                                                             'F'    [100.000183105,4656.62451172]
NhadJets                      NhadJets                      NhadJets                      NhadJets                                                        'F'    [2,19]
NbJets                        NbJets                        NbJets                        NbJets                                                          'F'    [0,8]
mTPhoMET_                     mTPhoMET_                     mTPhoMET_                     mTPhoMET_                                                       'F'    [0.000390765198972,5222.42333984]
dPhi_PhoMET_                  dPhi_PhoMET_                  dPhi_PhoMET_                  dPhi_PhoMET_                                                    'F'    [2.26497650146e-06,3.14158773422]
dPhi_Met_Jet1                 dPhi_Met_Jet1                 dPhi_Met_Jet1                 dPhi_Met_Jet1                                                   'F'    [0.300008535385,3.1415913105]
ST                            ST                            ST                            ST                                                              'F'    [300.000152588,8130.11474609]
NSpec 0


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDT_200trees_2maxdepthNode

#ifndef BDT_200trees_2maxdepthNode__def
#define BDT_200trees_2maxdepthNode__def

class BDT_200trees_2maxdepthNode {

public:

   // constructor of an essentially "empty" node floating in space
   BDT_200trees_2maxdepthNode ( BDT_200trees_2maxdepthNode* left,BDT_200trees_2maxdepthNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT_200trees_2maxdepthNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT_200trees_2maxdepthNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT_200trees_2maxdepthNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT_200trees_2maxdepthNode*   fLeft;     // pointer to the left daughter node
   BDT_200trees_2maxdepthNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDT_200trees_2maxdepthNode::~BDT_200trees_2maxdepthNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDT_200trees_2maxdepthNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDT_200trees_2maxdepthNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT_200trees_2maxdepth : public IClassifierReader {

 public:

   // constructor
   ReadBDT_200trees_2maxdepth( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDT_200trees_2maxdepth" ),
        fNvars( 7 )
   {
      // the training input variables
      const char* inputVars[] = { "MET", "NhadJets", "NbJets", "mTPhoMET_", "dPhi_PhoMET_", "dPhi_Met_Jet1", "ST" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT_200trees_2maxdepth() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[7];
   double fVmax[7];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[7];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT_200trees_2maxdepthNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT_200trees_2maxdepth::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT_200trees_2maxdepthNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT_200trees_2maxdepthNode*)current->GetRight();
         else current=(BDT_200trees_2maxdepthNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
}

void ReadBDT_200trees_2maxdepth::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(1.36548272033734);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 216.964, 0, 1, 0.920077,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.589812,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.00706849,-99) , 
3, 502.744, 0, 0, 0.0566686,-99) , 
6, 1386.77, 0, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(1.02146);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 340.636, 0, 1, 0.837929,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.607328,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0231793,-99) , 
0, 395.651, 0, 0, 0.108326,-99) , 
6, 1740.57, 0, 0, 0.432068,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.907925);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.935304,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.30688,-99) , 
0, 232.92, 0, 0, 0.776739,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525377,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0669762,-99) , 
0, 449.052, 0, 0, 0.15762,-99) , 
2, 1.5, 0, 0, 0.375127,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.841154);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.858245,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.323157,-99) , 
6, 1923.82, 0, 0, 0.627584,-99) , 
NN(
0, 
0, 
-1, 1068.27, 0, -1, 0.0749574,-99) , 
2, 0.5, 0, 0, 0.38685,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.564216);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.934157,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473453,-99) , 
3, 271.406, 0, 0, 0.754946,-99) , 
NN(
0, 
0, 
-1, 1064.14, 0, -1, 0.256362,-99) , 
2, 1.5, 0, 0, 0.442177,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.631768);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.860245,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417751,-99) , 
3, 210.797, 0, 0, 0.66579,-99) , 
NN(
0, 
0, 
-1, 763.665, 0, -1, 0.101224,-99) , 
6, 961.713, 0, 0, 0.519798,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.548899);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.763979,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400395,-99) , 
2, 0.5, 0, 0, 0.660442,-99) , 
NN(
0, 
0, 
-1, 1.5, 0, -1, 0.113221,-99) , 
6, 787.735, 0, 0, 0.555015,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.469245);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.726676,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.33664,-99) , 
6, 1090.33, 0, 0, 0.649931,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509301,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.166875,-99) , 
2, 1.5, 0, 0, 0.276224,-99) , 
0, 187.959, 0, 0, 0.539576,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.424512);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.822573,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.639133,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.30617,-99) , 
6, 2434.95, 0, 0, 0.431844,-99) , 
3, 722.778, 0, 0, 0.502927,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.356231);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.839266,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.629353,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.352595,-99) , 
3, 374.008, 0, 0, 0.446467,-99) , 
2, 2.5, 0, 0, 0.505317,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.202985);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.5, 0, 1, 0.572718,-99) , 
NN(
0, 
0, 
-1, 854.775, 0, -1, 0.285271,-99) , 
0, 153.352, 0, 0, 0.517251,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.279155);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.764494,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.604343,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.379512,-99) , 
6, 2842.91, 0, 0, 0.442344,-99) , 
2, 2.5, 0, 0, 0.485911,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.181218);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.76676,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51198,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.322032,-99) , 
4, 2.23487, 1, 0, 0.457883,-99) , 
0, 720.126, 0, 0, 0.503098,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.174524);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.732803,-99) , 
NN(
0, 
0, 
-1, 96.1062, 0, -1, 0.437771,-99) , 
0, 720.126, 0, 0, 0.479554,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.172939);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.917774, 1, 1, 0.567509,-99) , 
NN(
0, 
0, 
-1, 0.355917, 1, -1, 0.368967,-99) , 
3, 96.1062, 0, 0, 0.510911,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.162638);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.781068,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522858,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.351402,-99) , 
4, 1.92685, 1, 0, 0.467522,-99) , 
3, 1085.02, 0, 0, 0.492258,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.144843);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.687709,-99) , 
NN(
0, 
0, 
-1, 138.874, 0, -1, 0.444816,-99) , 
2, 2.5, 0, 0, 0.475489,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0959344);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.758451,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503071,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.293559,-99) , 
0, 127.677, 0, 0, 0.477876,-99) , 
3, 1016.94, 0, 0, 0.502533,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.172393);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.740443,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534387,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400611,-99) , 
5, 2.33574, 1, 0, 0.459568,-99) , 
3, 1016.94, 0, 0, 0.483751,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.108533);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.687799,-99) , 
NN(
0, 
0, 
-1, 566.164, 0, -1, 0.461236,-99) , 
0, 806.698, 0, 0, 0.48448,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.158977);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570583,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440942,-99) , 
3, 115.429, 0, 0, 0.526609,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.298323,-99) , 
6, 566.164, 0, 0, 0.50606,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.170546);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 617.981, 0, 1, 0.542716,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.616236,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.311869,-99) , 
1, 4.5, 0, 0, 0.412356,-99) , 
2, 0.5, 0, 0, 0.497998,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.102398);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.681728,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483488,-99) , 
3, 1085.02, 0, 0, 0.49985,-99) , 
NN(
0, 
0, 
-1, 875.807, 0, -1, 0.325312,-99) , 
0, 138.874, 0, 0, 0.474647,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0799354);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.5, 0, 1, 0.521271,-99) , 
NN(
0, 
0, 
-1, 875.807, 0, -1, 0.348176,-99) , 
0, 138.874, 0, 0, 0.496594,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.171079);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.748304,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452515,-99) , 
3, 106.521, 0, 0, 0.542885,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501737,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.226655,-99) , 
3, 250.676, 0, 0, 0.436244,-99) , 
4, 0.917774, 1, 0, 0.482259,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.17545);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.734812,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481076,-99) , 
3, 72.4788, 0, 0, 0.576828,-99) , 
NN(
0, 
0, 
-1, 130.588, 0, -1, 0.42068,-99) , 
4, 0.634086, 1, 0, 0.476373,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.164498);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.589903,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.162648,-99) , 
6, 708.312, 0, 0, 0.568749,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503857,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.29557,-99) , 
3, 320.167, 0, 0, 0.445578,-99) , 
4, 1.31216, 1, 0, 0.508475,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0931367);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.631964,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487843,-99) , 
2, 2.5, 0, 0, 0.505426,-99) , 
NN(
0, 
0, 
-1, 0.5, 0, -1, 0.353139,-99) , 
4, 2.7285, 1, 0, 0.480493,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.15728);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.685376,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493394,-99) , 
3, 148.46, 0, 0, 0.550396,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.609551,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.402918,-99) , 
3, 1004.61, 0, 0, 0.439294,-99) , 
4, 1.44626, 1, 0, 0.499008,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.120289);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 44.8475, 0, 1, 0.61992,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506925,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.268764,-99) , 
3, 129.942, 0, 0, 0.477478,-99) , 
4, 0.447142, 1, 0, 0.519573,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.123741);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 68.3073, 0, 1, 0.581076,-99) , 
NN(
0, 
0, 
-1, 129.942, 0, -1, 0.448822,-99) , 
4, 0.599816, 1, 0, 0.494732,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0798804);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 652.41, 0, 1, 0.526318,-99) , 
NN(
0, 
0, 
-1, 0.5, 0, -1, 0.390549,-99) , 
4, 2.7285, 1, 0, 0.50421,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.115594);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.589309,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466646,-99) , 
5, 2.04629, 1, 0, 0.502491,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.346312,-99) , 
5, 0.680813, 0, 0, 0.490721,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0684445);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.609539,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508056,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393302,-99) , 
4, 2.72823, 1, 0, 0.489631,-99) , 
2, 2.5, 0, 0, 0.504015,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0644768);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593132,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501397,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4267,-99) , 
0, 446.016, 1, 0, 0.477983,-99) , 
2, 2.5, 0, 0, 0.491725,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.112753);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.618485,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553842,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450364,-99) , 
4, 0.285127, 1, 0, 0.472426,-99) , 
0, 867.721, 0, 0, 0.484475,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0948807);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.672763,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486732,-99) , 
4, 0.735537, 1, 0, 0.519108,-99) , 
NN(
0, 
0, 
-1, 0.356978, 1, -1, 0.435223,-99) , 
3, 83.351, 0, 0, 0.496952,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.099541);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.84982, 1, 1, 0.557966,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518435,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39317,-99) , 
4, 0.917774, 1, 0, 0.482934,-99) , 
3, 293.645, 0, 0, 0.514649,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0807218);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.663699,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497808,-99) , 
4, 1.08463, 1, 0, 0.527975,-99) , 
NN(
0, 
0, 
-1, 0.44728, 1, -1, 0.444146,-99) , 
3, 129.817, 0, 0, 0.497911,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0957873);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.54568, 1, 1, 0.540913,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515762,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.29518,-99) , 
4, 0.44728, 1, 0, 0.464154,-99) , 
3, 129.817, 0, 0, 0.513419,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0702152);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.606354,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488982,-99) , 
4, 0.344109, 1, 0, 0.506727,-99) , 
NN(
0, 
0, 
-1, 0.109639, 1, -1, 0.389544,-99) , 
3, 32.4359, 0, 0, 0.493471,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0773152);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.735537, 1, 1, 0.5305,-99) , 
NN(
0, 
0, 
-1, 0.285127, 1, -1, 0.438868,-99) , 
3, 83.2629, 0, 0, 0.506328,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0721436);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.59409,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50901,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429288,-99) , 
0, 449.506, 1, 0, 0.484194,-99) , 
2, 2.5, 0, 0, 0.497193,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0552744);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.617556,-99) , 
NN(
0, 
0, 
-1, 2.37593, 1, -1, 0.479243,-99) , 
3, 1085.02, 0, 0, 0.489033,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0830851);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555137,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479158,-99) , 
5, 2.32161, 1, 0, 0.510734,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.381437,-99) , 
5, 0.689586, 0, 0, 0.500893,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.192244);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.582692,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41795,-99) , 
1, 6.5, 1, 0, 0.530387,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.613055,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.377747,-99) , 
1, 4.5, 0, 0, 0.457941,-99) , 
2, 0.5, 0, 0, 0.505731,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0433755);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.589767,-99) , 
NN(
0, 
0, 
-1, 109.373, 0, -1, 0.48737,-99) , 
2, 2.5, 0, 0, 0.499375,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0722851);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.582112,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512442,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.409265,-99) , 
0, 430.634, 1, 0, 0.493142,-99) , 
0, 636.113, 0, 0, 0.507682,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0448183);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.592465,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491563,-99) , 
3, 932.161, 0, 0, 0.501539,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.319061,-99) , 
0, 109.373, 0, 0, 0.49526,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0601866);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519318,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407524,-99) , 
5, 0.721886, 0, 0, 0.510534,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.328876,-99) , 
0, 109.373, 0, 0, 0.504328,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0373031);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506428,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417265,-99) , 
3, 28.0332, 0, 0, 0.497853,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.342295,-99) , 
0, 109.373, 0, 0, 0.492583,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0603539);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563506,-99) , 
NN(
0, 
0, 
-1, 53.5401, 0, -1, 0.474584,-99) , 
4, 0.150355, 1, 0, 0.485613,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.115665);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.659159,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479227,-99) , 
4, 2.22882, 1, 0, 0.538272,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559359,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448469,-99) , 
6, 1386.09, 1, 0, 0.477913,-99) , 
3, 414.783, 0, 0, 0.49695,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.112132);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566883,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560422,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452035,-99) , 
2, 1.5, 0, 0, 0.492978,-99) , 
6, 3144.4, 0, 0, 0.509416,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.078382);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.576484,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519085,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445767,-99) , 
4, 1.54516, 1, 0, 0.494014,-99) , 
3, 652.41, 0, 0, 0.508565,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.0684292);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.622495,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499523,-99) , 
4, 1.90772, 1, 0, 0.535875,-99) , 
NN(
0, 
0, 
-1, 708.312, 0, -1, 0.46797,-99) , 
3, 250.778, 0, 0, 0.500011,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0925524);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 2.37755, 1, 1, 0.55264,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531533,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447354,-99) , 
4, 0.488931, 1, 0, 0.488577,-99) , 
3, 346.975, 0, 0, 0.51237,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0725367);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.566666, 1, 1, 0.52333,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512552,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.279515,-99) , 
4, 0.184198, 1, 0, 0.43178,-99) , 
3, 62.8068, 0, 0, 0.504099,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0721817);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.594669,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485117,-99) , 
4, 0.357671, 1, 0, 0.501369,-99) , 
NN(
0, 
0, 
-1, 0.109639, 1, -1, 0.39806,-99) , 
3, 34.9427, 0, 0, 0.488582,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0631712);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.650975, 1, 1, 0.521535,-99) , 
NN(
0, 
0, 
-1, 0.226917, 1, -1, 0.433512,-99) , 
3, 68.193, 0, 0, 0.501936,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0723597);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.613789,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486724,-99) , 
4, 1.08463, 1, 0, 0.511388,-99) , 
NN(
0, 
0, 
-1, 708.309, 0, -1, 0.457332,-99) , 
3, 119.912, 0, 0, 0.493165,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0675591);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.595357,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520921,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452899,-99) , 
0, 396.257, 1, 0, 0.499848,-99) , 
3, 1085.02, 0, 0, 0.506611,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0360657);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560116,-99) , 
NN(
0, 
0, 
-1, 28.0332, 0, -1, 0.489131,-99) , 
0, 669.156, 0, 0, 0.499447,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.0673811);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.60291,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499075,-99) , 
4, 1.65164, 1, 0, 0.526657,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513525,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.374671,-99) , 
4, 0.634086, 1, 0, 0.479804,-99) , 
3, 183.429, 0, 0, 0.505846,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.0643827);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 961.885, 1, 1, 0.529874,-99) , 
NN(
0, 
0, 
-1, 708.309, 0, -1, 0.46372,-99) , 
3, 129.817, 0, 0, 0.506401,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0559239);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566302,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508193,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.30998,-99) , 
3, 53.5401, 0, 0, 0.492594,-99) , 
4, 0.148726, 1, 0, 0.501732,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.0691087);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580989,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.351218,-99) , 
1, 3.5, 0, 0, 0.54242,-99) , 
NN(
0, 
0, 
-1, 88.9097, 0, -1, 0.478142,-99) , 
4, 0.229202, 1, 0, 0.489666,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.0480386);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.599971,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496352,-99) , 
4, 0.308136, 1, 0, 0.511165,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415244,-99) , 
3, 28.0332, 0, 0, 0.501788,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.0635026);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.428629, 1, 1, 0.522578,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520014,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.284042,-99) , 
4, 0.145893, 1, 0, 0.445671,-99) , 
3, 44.8475, 0, 0, 0.51071,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.0480041);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57975,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492819,-99) , 
4, 0.308136, 1, 0, 0.505114,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415531,-99) , 
3, 28.0332, 0, 0, 0.496375,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.0553161);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 961.885, 1, 1, 0.522603,-99) , 
NN(
0, 
0, 
-1, 714.376, 0, -1, 0.458862,-99) , 
3, 88.9097, 0, 0, 0.505317,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0590664);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520488,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406996,-99) , 
5, 0.547818, 0, 0, 0.512272,-99) , 
NN(
0, 
0, 
-1, 473.951, 0, -1, 0.459245,-99) , 
5, 2.82388, 1, 0, 0.498989,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0735241);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559981,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532071,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464774,-99) , 
6, 1386.09, 1, 0, 0.486128,-99) , 
3, 932.161, 0, 0, 0.493213,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.10836);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569712,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459553,-99) , 
4, 1.16404, 1, 0, 0.524479,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5226,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.401345,-99) , 
2, 0.5, 0, 0, 0.477087,-99) , 
6, 2217.18, 0, 0, 0.497512,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.0650346);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.659805,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49699,-99) , 
3, 592.971, 0, 0, 0.519885,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50586,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.383738,-99) , 
3, 130.588, 0, 0, 0.470271,-99) , 
6, 2222.95, 0, 0, 0.491539,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0690363);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 589.448, 0, 1, 0.531618,-99) , 
NN(
0, 
0, 
-1, 393.044, 1, -1, 0.4634,-99) , 
6, 2222.95, 0, 0, 0.492657,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.0357085);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552771,-99) , 
NN(
0, 
0, 
-1, 42.7, 0, -1, 0.487036,-99) , 
4, 0.148823, 1, 0, 0.4951,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.0413051);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.587515,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495957,-99) , 
4, 0.304259, 1, 0, 0.508942,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433746,-99) , 
3, 27.1507, 0, 0, 0.501837,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0593563);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.428629, 1, 1, 0.518528,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543871,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.332867,-99) , 
4, 0.109639, 1, 0, 0.456727,-99) , 
3, 42.7, 0, 0, 0.509518,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.0196164);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.744152,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495182,-99) , 
6, 357.928, 1, 0, 0.498408,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.281191,-99) , 
6, 338.626, 0, 0, 0.496464,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.0101443);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 357.928, 1, 1, 0.503185,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.285173,-99) , 
6, 338.626, 0, 0, 0.501242,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.0146617);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.738445,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49755,-99) , 
6, 357.928, 1, 0, 0.500649,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.287246,-99) , 
6, 338.626, 0, 0, 0.498751,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.0120873);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 357.928, 1, 1, 0.504221,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.290257,-99) , 
6, 338.626, 0, 0, 0.502323,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.0403161);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577805,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494047,-99) , 
4, 0.291765, 1, 0, 0.505584,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436434,-99) , 
3, 25.8041, 0, 0, 0.499355,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.0623799);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563134,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483128,-99) , 
4, 2.37756, 1, 0, 0.526075,-99) , 
NN(
0, 
0, 
-1, 708.312, 0, -1, 0.48237,-99) , 
3, 183.429, 0, 0, 0.506912,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.0282546);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.458285,-99) , 
NN(
0, 
0, 
-1, 1004.61, 0, 1, 0.513791,-99) , 
6, 341.386, 1, 0, 0.513129,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.0141273);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.465307,-99) , 
NN(
0, 
0, 
-1, 1004.61, 0, 1, 0.50673,-99) , 
6, 341.386, 1, 0, 0.506236,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.0155568);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.468824,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.564057,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497656,-99) , 
3, 1004.61, 0, 0, 0.503199,-99) , 
6, 341.386, 1, 0, 0.502789,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.0389627);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.4727,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518615,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478898,-99) , 
0, 446.016, 1, 0, 0.506439,-99) , 
6, 341.386, 1, 0, 0.506037,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.0197272);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.482421,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555505,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496004,-99) , 
3, 871.986, 0, 0, 0.502673,-99) , 
6, 341.386, 1, 0, 0.502432,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.0153832);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.487348,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557313,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499355,-99) , 
4, 0.148823, 1, 0, 0.506501,-99) , 
6, 341.386, 1, 0, 0.506273,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.0348223);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.491192,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514653,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450495,-99) , 
5, 0.721875, 0, 0, 0.509399,-99) , 
6, 341.386, 1, 0, 0.509183,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.0158914);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.499897,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560858,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496771,-99) , 
3, 1004.61, 0, 0, 0.502122,-99) , 
6, 341.386, 1, 0, 0.502095,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.0108266);
  fForest.push_back( 
NN(
0, 
0, 
-1, 341.386, 1, 1, 0.505413,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.00541328);
  fForest.push_back( 
NN(
0, 
0, 
-1, 341.386, 1, 1, 0.502707,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.0041873);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.499809,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.668599,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499624,-99) , 
6, 360.924, 1, 0, 0.501372,-99) , 
6, 341.386, 1, 0, 0.501353,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.0247934);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500856,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508411,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45495,-99) , 
3, 32.4359, 0, 0, 0.502397,-99) , 
6, 341.386, 1, 0, 0.502379,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.0293849);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.494658,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548312,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49013,-99) , 
4, 0.156723, 1, 0, 0.497593,-99) , 
6, 341.386, 1, 0, 0.497558,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.0226642);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502004,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507817,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442271,-99) , 
3, 19.6302, 0, 0, 0.503055,-99) , 
6, 341.386, 1, 0, 0.503043,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.0237074);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.496338,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546889,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492296,-99) , 
4, 0.129272, 1, 0, 0.498212,-99) , 
6, 341.386, 1, 0, 0.49819,-99)    );
  // itree = 100
  fBoostWeights.push_back(0.0315686);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502265,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512017,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469966,-99) , 
3, 68.1886, 0, 0, 0.502855,-99) , 
6, 341.386, 1, 0, 0.502848,-99)    );
  // itree = 101
  fBoostWeights.push_back(0.0286601);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.494373,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542078,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490543,-99) , 
4, 0.18967, 1, 0, 0.498401,-99) , 
6, 341.386, 1, 0, 0.498353,-99)    );
  // itree = 102
  fBoostWeights.push_back(0.00672095);
  fForest.push_back( 
NN(
0, 
0, 
-1, 341.386, 1, 1, 0.50336,-99)    );
  // itree = 103
  fBoostWeights.push_back(0.00349737);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.499858,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.667965,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499967,-99) , 
6, 360.924, 1, 0, 0.501702,-99) , 
6, 341.386, 1, 0, 0.50168,-99)    );
  // itree = 104
  fBoostWeights.push_back(0.0233512);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500732,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507898,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449021,-99) , 
3, 25.8041, 0, 0, 0.502559,-99) , 
6, 341.386, 1, 0, 0.502537,-99)    );
  // itree = 105
  fBoostWeights.push_back(0.0111105);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.494894,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.662439,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496069,-99) , 
6, 360.924, 1, 0, 0.497779,-99) , 
6, 341.386, 1, 0, 0.497745,-99)    );
  // itree = 106
  fBoostWeights.push_back(0.00555527);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.497672,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.65995,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498847,-99) , 
6, 360.924, 1, 0, 0.5005,-99) , 
6, 341.386, 1, 0, 0.500466,-99)    );
  // itree = 107
  fBoostWeights.push_back(0.0155106);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.499061,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551943,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496704,-99) , 
4, 0.109671, 1, 0, 0.50186,-99) , 
6, 341.386, 1, 0, 0.501827,-99)    );
  // itree = 108
  fBoostWeights.push_back(0.0125301);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502938,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549694,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499272,-99) , 
2, 2.5, 0, 0, 0.505014,-99) , 
6, 341.386, 1, 0, 0.50499,-99)    );
  // itree = 109
  fBoostWeights.push_back(0.0146962);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.499806,-99) , 
NN(
0, 
0, 
-1, 360.924, 1, 1, 0.507434,-99) , 
6, 341.386, 1, 0, 0.507343,-99)    );
  // itree = 110
  fBoostWeights.push_back(0.00751419);
  fForest.push_back( 
NN(
0, 
0, 
-1, 341.386, 1, 1, 0.503757,-99)    );
  // itree = 111
  fBoostWeights.push_back(0.0037571);
  fForest.push_back( 
NN(
0, 
0, 
-1, 341.386, 1, 1, 0.501879,-99)    );
  // itree = 112
  fBoostWeights.push_back(0.00459999);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500662,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.658947,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499304,-99) , 
6, 360.924, 1, 0, 0.500943,-99) , 
6, 341.386, 1, 0, 0.500939,-99)    );
  // itree = 113
  fBoostWeights.push_back(0.0149636);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.499512,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504979,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41512,-99) , 
0, 109.373, 0, 0, 0.502069,-99) , 
6, 341.386, 1, 0, 0.502039,-99)    );
  // itree = 114
  fBoostWeights.push_back(0.00916561);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503253,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.654958,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496955,-99) , 
6, 360.924, 1, 0, 0.49857,-99) , 
6, 341.386, 1, 0, 0.498626,-99)    );
  // itree = 115
  fBoostWeights.push_back(0.0214219);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500961,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506598,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457502,-99) , 
4, 2.84639, 1, 0, 0.500815,-99) , 
6, 341.386, 1, 0, 0.500817,-99)    );
  // itree = 116
  fBoostWeights.push_back(0.029887);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.495606,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532544,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488799,-99) , 
3, 652.41, 0, 0, 0.49672,-99) , 
6, 341.386, 1, 0, 0.496707,-99)    );
  // itree = 117
  fBoostWeights.push_back(0.0307545);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503078,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519452,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487532,-99) , 
6, 2217.18, 0, 0, 0.501486,-99) , 
6, 341.386, 1, 0, 0.501505,-99)    );
  // itree = 118
  fBoostWeights.push_back(0.0226113);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.495389,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536102,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494476,-99) , 
6, 963.632, 1, 0, 0.502454,-99) , 
6, 341.386, 1, 0, 0.502369,-99)    );
  // itree = 119
  fBoostWeights.push_back(0.0246806);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501042,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509769,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443122,-99) , 
3, 15.4474, 0, 0, 0.505941,-99) , 
6, 341.386, 1, 0, 0.505883,-99)    );
  // itree = 120
  fBoostWeights.push_back(0.0289044);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.494872,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526989,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49024,-99) , 
4, 0.428627, 1, 0, 0.50048,-99) , 
6, 341.386, 1, 0, 0.500413,-99)    );
  // itree = 121
  fBoostWeights.push_back(0.0303868);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502098,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511466,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465732,-99) , 
3, 50.6112, 0, 0, 0.50368,-99) , 
6, 341.386, 1, 0, 0.503662,-99)    );
  // itree = 122
  fBoostWeights.push_back(0.0215203);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.494501,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550917,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493299,-99) , 
4, 0.109671, 1, 0, 0.49867,-99) , 
6, 341.386, 1, 0, 0.49862,-99)    );
  // itree = 123
  fBoostWeights.push_back(0.0318977);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.499881,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51498,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48181,-99) , 
0, 393.552, 1, 0, 0.503047,-99) , 
6, 341.386, 1, 0, 0.50301,-99)    );
  // itree = 124
  fBoostWeights.push_back(0.0173312);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507855,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556715,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49571,-99) , 
3, 1004.61, 0, 0, 0.500811,-99) , 
6, 341.386, 1, 0, 0.500896,-99)    );
  // itree = 125
  fBoostWeights.push_back(0.0100331);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503523,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556878,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499665,-99) , 
0, 869.16, 0, 0, 0.50442,-99) , 
6, 341.386, 1, 0, 0.504409,-99)    );
  // itree = 126
  fBoostWeights.push_back(0.0128924);
  fForest.push_back( 
NN(
0, 
0, 
-1, 341.386, 1, 1, 0.506446,-99)    );
  // itree = 127
  fBoostWeights.push_back(0.00655193);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.497791,-99) , 
NN(
0, 
0, 
-1, 360.924, 1, 1, 0.503289,-99) , 
6, 341.386, 1, 0, 0.503223,-99)    );
  // itree = 128
  fBoostWeights.push_back(0.00327596);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.499429,-99) , 
NN(
0, 
0, 
-1, 360.924, 1, 1, 0.501651,-99) , 
6, 341.386, 1, 0, 0.501624,-99)    );
  // itree = 129
  fBoostWeights.push_back(0.00445705);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500248,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.651189,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499282,-99) , 
6, 360.924, 1, 0, 0.500832,-99) , 
6, 341.386, 1, 0, 0.500825,-99)    );
  // itree = 130
  fBoostWeights.push_back(0.0259438);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.499134,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525313,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492039,-99) , 
3, 440.266, 0, 0, 0.501923,-99) , 
6, 341.386, 1, 0, 0.50189,-99)    );
  // itree = 131
  fBoostWeights.push_back(0.0172731);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50562,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54279,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497566,-99) , 
4, 0.193558, 1, 0, 0.504557,-99) , 
6, 341.386, 1, 0, 0.50457,-99)    );
  // itree = 132
  fBoostWeights.push_back(0.0308219);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501302,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513014,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464067,-99) , 
3, 32.4359, 0, 0, 0.507542,-99) , 
6, 341.386, 1, 0, 0.507467,-99)    );
  // itree = 133
  fBoostWeights.push_back(0.0198418);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.493597,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547131,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495214,-99) , 
4, 0.148814, 1, 0, 0.501561,-99) , 
6, 341.386, 1, 0, 0.501465,-99)    );
  // itree = 134
  fBoostWeights.push_back(0.0278581);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.498557,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510989,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462821,-99) , 
4, 2.84639, 1, 0, 0.505309,-99) , 
6, 341.386, 1, 0, 0.505228,-99)    );
  // itree = 135
  fBoostWeights.push_back(0.00628235);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505521,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.651941,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498421,-99) , 
6, 360.924, 1, 0, 0.499987,-99) , 
6, 341.386, 1, 0, 0.500054,-99)    );
  // itree = 136
  fBoostWeights.push_back(0.00314117);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503951,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.650514,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499992,-99) , 
6, 360.924, 1, 0, 0.501526,-99) , 
6, 341.386, 1, 0, 0.501555,-99)    );
  // itree = 137
  fBoostWeights.push_back(0.00461128);
  fForest.push_back( 
NN(
0, 
0, 
-1, 341.386, 1, 1, 0.502306,-99)    );
  // itree = 138
  fBoostWeights.push_back(0.00377463);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502013,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.64875,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499624,-99) , 
6, 360.924, 1, 0, 0.501142,-99) , 
6, 341.386, 1, 0, 0.501153,-99)    );
  // itree = 139
  fBoostWeights.push_back(0.00410983);
  fForest.push_back( 
NN(
0, 
0, 
-1, 341.386, 1, 1, 0.502055,-99)    );
  // itree = 140
  fBoostWeights.push_back(0.00385174);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500041,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.646951,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499541,-99) , 
6, 360.924, 1, 0, 0.501039,-99) , 
6, 341.386, 1, 0, 0.501027,-99)    );
  // itree = 141
  fBoostWeights.push_back(0.0153382);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.499079,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542785,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496746,-99) , 
2, 2.5, 0, 0, 0.501983,-99) , 
6, 341.386, 1, 0, 0.501948,-99)    );
  // itree = 142
  fBoostWeights.push_back(0.00984272);
  fForest.push_back( 
NN(
0, 
0, 
-1, 341.386, 1, 1, 0.504921,-99)    );
  // itree = 143
  fBoostWeights.push_back(0.00492136);
  fForest.push_back( 
NN(
0, 
0, 
-1, 341.386, 1, 1, 0.502461,-99)    );
  // itree = 144
  fBoostWeights.push_back(0.00340881);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.499222,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.646103,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499767,-99) , 
6, 360.924, 1, 0, 0.501255,-99) , 
6, 341.386, 1, 0, 0.50123,-99)    );
  // itree = 145
  fBoostWeights.push_back(0.00413089);
  fForest.push_back( 
NN(
0, 
0, 
-1, 341.386, 1, 1, 0.502065,-99)    );
  // itree = 146
  fBoostWeights.push_back(0.00372842);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.499042,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.644377,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499587,-99) , 
6, 360.924, 1, 0, 0.501057,-99) , 
6, 341.386, 1, 0, 0.501033,-99)    );
  // itree = 147
  fBoostWeights.push_back(0.00389355);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.499974,-99) , 
NN(
0, 
0, 
-1, 360.924, 1, 1, 0.50197,-99) , 
6, 341.386, 1, 0, 0.501946,-99)    );
  // itree = 148
  fBoostWeights.push_back(0.00377073);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500947,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.642629,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499545,-99) , 
6, 360.924, 1, 0, 0.500997,-99) , 
6, 341.386, 1, 0, 0.500996,-99)    );
  // itree = 149
  fBoostWeights.push_back(0.0135084);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500004,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504524,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423911,-99) , 
0, 109.373, 0, 0, 0.50192,-99) , 
6, 341.386, 1, 0, 0.501897,-99)    );
  // itree = 150
  fBoostWeights.push_back(0.0080858);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.496627,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.639034,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497328,-99) , 
6, 360.924, 1, 0, 0.498761,-99) , 
6, 341.386, 1, 0, 0.498736,-99)    );
  // itree = 151
  fBoostWeights.push_back(0.0143734);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.498649,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504244,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443517,-99) , 
3, 15.4474, 0, 0, 0.500742,-99) , 
6, 341.386, 1, 0, 0.500717,-99)    );
  // itree = 152
  fBoostWeights.push_back(0.0211461);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502242,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544195,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492772,-99) , 
4, 0.109671, 1, 0, 0.497563,-99) , 
6, 341.386, 1, 0, 0.497619,-99)    );
  // itree = 153
  fBoostWeights.push_back(0.0185686);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.496956,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506051,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448412,-99) , 
3, 19.6302, 0, 0, 0.501864,-99) , 
6, 341.386, 1, 0, 0.501806,-99)    );
  // itree = 154
  fBoostWeights.push_back(0.0278018);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501598,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518369,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488035,-99) , 
4, 0.555263, 1, 0, 0.497896,-99) , 
6, 341.386, 1, 0, 0.497941,-99)    );
  // itree = 155
  fBoostWeights.push_back(0.0303557);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.494647,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50997,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465469,-99) , 
3, 68.1886, 0, 0, 0.500328,-99) , 
6, 341.386, 1, 0, 0.50026,-99)    );
  // itree = 156
  fBoostWeights.push_back(0.0231124);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502236,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541325,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491377,-99) , 
4, 0.109671, 1, 0, 0.496026,-99) , 
6, 341.386, 1, 0, 0.496101,-99)    );
  // itree = 157
  fBoostWeights.push_back(0.0212414);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.496458,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506641,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464164,-99) , 
3, 40.6567, 0, 0, 0.500729,-99) , 
6, 341.386, 1, 0, 0.500677,-99)    );
  // itree = 158
  fBoostWeights.push_back(0.0261207);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501768,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528778,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490118,-99) , 
4, 0.22962, 1, 0, 0.496896,-99) , 
6, 341.386, 1, 0, 0.496954,-99)    );
  // itree = 159
  fBoostWeights.push_back(0.0285403);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.495238,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510771,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476315,-99) , 
3, 93.8261, 0, 0, 0.501137,-99) , 
6, 341.386, 1, 0, 0.501066,-99)    );
  // itree = 160
  fBoostWeights.push_back(0.0298207);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502373,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517382,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486338,-99) , 
0, 234.245, 1, 0, 0.497991,-99) , 
6, 341.386, 1, 0, 0.498044,-99)    );
  // itree = 161
  fBoostWeights.push_back(0.031928);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.494918,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517192,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484861,-99) , 
0, 321.375, 0, 0, 0.499849,-99) , 
6, 341.386, 1, 0, 0.49979,-99)    );
  // itree = 162
  fBoostWeights.push_back(0.0278911);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5029,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510412,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47751,-99) , 
0, 449.506, 1, 0, 0.500431,-99) , 
6, 341.386, 1, 0, 0.50046,-99)    );
  // itree = 163
  fBoostWeights.push_back(0.0290255);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.495927,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520498,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487884,-99) , 
4, 0.488931, 1, 0, 0.497688,-99) , 
6, 341.386, 1, 0, 0.497667,-99)    );
  // itree = 164
  fBoostWeights.push_back(0.0178243);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503184,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542654,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49527,-99) , 
3, 871.986, 0, 0, 0.500582,-99) , 
6, 341.386, 1, 0, 0.500613,-99)    );
  // itree = 165
  fBoostWeights.push_back(0.0236485);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.498728,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508854,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459219,-99) , 
3, 28.0332, 0, 0, 0.504039,-99) , 
6, 341.386, 1, 0, 0.503975,-99)    );
  // itree = 166
  fBoostWeights.push_back(0.0171874);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50464,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542453,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494835,-99) , 
4, 0.109671, 1, 0, 0.499274,-99) , 
6, 341.386, 1, 0, 0.499339,-99)    );
  // itree = 167
  fBoostWeights.push_back(0.0274619);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500343,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517423,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489346,-99) , 
3, 250.778, 0, 0, 0.50277,-99) , 
6, 341.386, 1, 0, 0.502741,-99)    );
  // itree = 168
  fBoostWeights.push_back(0.0283011);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.493478,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523039,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491056,-99) , 
4, 0.735527, 1, 0, 0.503072,-99) , 
6, 341.386, 1, 0, 0.502956,-99)    );
  // itree = 169
  fBoostWeights.push_back(0.0291756);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500553,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512275,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475462,-99) , 
3, 62.8068, 0, 0, 0.504833,-99) , 
6, 341.386, 1, 0, 0.504781,-99)    );
  // itree = 170
  fBoostWeights.push_back(0.0205221);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.493259,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535676,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494219,-99) , 
4, 0.18967, 1, 0, 0.500489,-99) , 
6, 341.386, 1, 0, 0.500402,-99)    );
  // itree = 171
  fBoostWeights.push_back(0.00807696);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.498389,-99) , 
NN(
0, 
0, 
-1, 360.924, 1, 1, 0.504068,-99) , 
6, 341.386, 1, 0, 0.504,-99)    );
  // itree = 172
  fBoostWeights.push_back(0.00405816);
  fForest.push_back( 
NN(
0, 
0, 
-1, 341.386, 1, 1, 0.502029,-99)    );
  // itree = 173
  fBoostWeights.push_back(0.00380544);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.499394,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.644637,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499553,-99) , 
6, 360.924, 1, 0, 0.501034,-99) , 
6, 341.386, 1, 0, 0.501015,-99)    );
  // itree = 174
  fBoostWeights.push_back(0.00389347);
  fForest.push_back( 
NN(
0, 
0, 
-1, 341.386, 1, 1, 0.501947,-99)    );
  // itree = 175
  fBoostWeights.push_back(0.00381025);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.499372,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.642872,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499531,-99) , 
6, 360.924, 1, 0, 0.500993,-99) , 
6, 341.386, 1, 0, 0.500973,-99)    );
  // itree = 176
  fBoostWeights.push_back(0.00381352);
  fForest.push_back( 
NN(
0, 
0, 
-1, 341.386, 1, 1, 0.501907,-99)    );
  // itree = 177
  fBoostWeights.push_back(0.00377353);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.499371,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.64112,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49953,-99) , 
6, 360.924, 1, 0, 0.500973,-99) , 
6, 341.386, 1, 0, 0.500953,-99)    );
  // itree = 178
  fBoostWeights.push_back(0.00375559);
  fForest.push_back( 
NN(
0, 
0, 
-1, 341.386, 1, 1, 0.501878,-99)    );
  // itree = 179
  fBoostWeights.push_back(0.00372683);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.499376,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.639385,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499535,-99) , 
6, 360.924, 1, 0, 0.500958,-99) , 
6, 341.386, 1, 0, 0.500939,-99)    );
  // itree = 180
  fBoostWeights.push_back(0.0276693);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500307,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514111,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486151,-99) , 
5, 2.53225, 1, 0, 0.501871,-99) , 
6, 341.386, 1, 0, 0.501852,-99)    );
  // itree = 181
  fBoostWeights.push_back(0.0178888);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.49339,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505439,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451699,-99) , 
5, 0.721875, 0, 0, 0.50101,-99) , 
6, 341.386, 1, 0, 0.500919,-99)    );
  // itree = 182
  fBoostWeights.push_back(0.0106491);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.497862,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.630973,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495915,-99) , 
6, 360.924, 1, 0, 0.497275,-99) , 
6, 341.386, 1, 0, 0.497282,-99)    );
  // itree = 183
  fBoostWeights.push_back(0.0146407);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500525,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543803,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495899,-99) , 
0, 869.16, 0, 0, 0.499884,-99) , 
6, 341.386, 1, 0, 0.499891,-99)    );
  // itree = 184
  fBoostWeights.push_back(0.0238716);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.496864,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519938,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492709,-99) , 
0, 234.245, 1, 0, 0.502935,-99) , 
6, 341.386, 1, 0, 0.502862,-99)    );
  // itree = 185
  fBoostWeights.push_back(0.0284383);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502832,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518729,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490043,-99) , 
0, 298.334, 0, 0, 0.504422,-99) , 
6, 341.386, 1, 0, 0.504403,-99)    );
  // itree = 186
  fBoostWeights.push_back(0.0301662);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.495723,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515327,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484997,-99) , 
0, 393.552, 1, 0, 0.504406,-99) , 
6, 341.386, 1, 0, 0.504301,-99)    );
  // itree = 187
  fBoostWeights.push_back(0.0194654);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503264,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534914,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495455,-99) , 
0, 618.04, 0, 0, 0.502296,-99) , 
6, 341.386, 1, 0, 0.502308,-99)    );
  // itree = 188
  fBoostWeights.push_back(0.0195566);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.498398,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507932,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431695,-99) , 
0, 109.373, 0, 0, 0.505476,-99) , 
6, 341.386, 1, 0, 0.505391,-99)    );
  // itree = 189
  fBoostWeights.push_back(0.0137991);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503287,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504164,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447889,-99) , 
3, 15.4474, 0, 0, 0.500902,-99) , 
6, 341.386, 1, 0, 0.500931,-99)    );
  // itree = 190
  fBoostWeights.push_back(0.0206279);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.499837,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533987,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492834,-99) , 
4, 0.148814, 1, 0, 0.497852,-99) , 
6, 341.386, 1, 0, 0.497876,-99)    );
  // itree = 191
  fBoostWeights.push_back(0.0173689);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504994,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505652,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452133,-99) , 
3, 19.6302, 0, 0, 0.501752,-99) , 
6, 341.386, 1, 0, 0.501791,-99)    );
  // itree = 192
  fBoostWeights.push_back(0.00884444);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500652,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.625165,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496755,-99) , 
6, 360.924, 1, 0, 0.498042,-99) , 
6, 341.386, 1, 0, 0.498074,-99)    );
  // itree = 193
  fBoostWeights.push_back(0.0156759);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.498441,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535848,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495655,-99) , 
2, 2.5, 0, 0, 0.500209,-99) , 
6, 341.386, 1, 0, 0.500188,-99)    );
  // itree = 194
  fBoostWeights.push_back(0.00645959);
  fForest.push_back( 
NN(
0, 
0, 
-1, 341.386, 1, 1, 0.50323,-99)    );
  // itree = 195
  fBoostWeights.push_back(0.0032298);
  fForest.push_back( 
NN(
0, 
0, 
-1, 341.386, 1, 1, 0.501615,-99)    );
  // itree = 196
  fBoostWeights.push_back(0.00331458);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.499938,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.624391,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499566,-99) , 
6, 360.924, 1, 0, 0.500818,-99) , 
6, 341.386, 1, 0, 0.500807,-99)    );
  // itree = 197
  fBoostWeights.push_back(0.0204251);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500766,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507186,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47413,-99) , 
4, 2.70465, 1, 0, 0.50163,-99) , 
6, 341.386, 1, 0, 0.50162,-99)    );
  // itree = 198
  fBoostWeights.push_back(0.0173388);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.49566,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54177,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494283,-99) , 
3, 1004.61, 0, 0, 0.49824,-99) , 
6, 341.386, 1, 0, 0.498209,-99)    );
  // itree = 199
  fBoostWeights.push_back(0.0178454);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -1, 0.499995,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528583,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495567,-99) , 
6, 963.632, 1, 0, 0.501853,-99) , 
6, 341.386, 1, 0, 0.50183,-99)    );
   return;
};

// Clean up
inline void ReadBDT_200trees_2maxdepth::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDT_200trees_2maxdepth::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
