#!/bin/bash
string=$1
cp FullRun2_ZNuNu_PhoIdloose_phopt40_${string}.root FullRun2_ZNuNu_PhoIdloose_phopt40.root
cp FullRun2_WJetsToLNu_HT_PhoIdloose_phopt40_${string}.root FullRun2_WJetsToLNu_HT_PhoIdloose_phopt40.root
cp FullRun2_WGJets_PhoIdloose_phopt40_${string}.root FullRun2_WGJets_PhoIdloose_phopt40.root
cp FullRun2_TTJets_PhoIdloose_phopt40_${string}.root FullRun2_TTJets_PhoIdloose_phopt40.root
cp FullRun2_TTGJets_inc_PhoIdloose_phopt40_${string}.root FullRun2_TTGJets_inc_PhoIdloose_phopt40.root
cp FullRun2_GJets_QCD_PhoIdloose_phopt40_${string}.root FullRun2_GJets_QCD_PhoIdloose_phopt40.root

